name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: ${{ matrix.platform }} on Xcode ${{ matrix.xcode }}
    runs-on: macos-13
    strategy:
      matrix:
        platform: [macOS, iOS, tvOS, watchOS]
        xcode: [^14] # ^15
    steps:
      - uses: actions/checkout@v4

      - name: Xcode Build
        uses: mxcl/xcodebuild@v1
        with:
          xcode: ${{ matrix.xcode }}
          platform: ${{ matrix.platform }}
          action: build
          configuration: debug
          scheme: Aptabase

      - name: Xcode Test
        uses: mxcl/xcodebuild@v1
        with:
          xcode: ${{ matrix.xcode }}
          platform: ${{ matrix.platform }}
          action: test
          configuration: debug
          scheme: AptabaseTests