name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: ${{ matrix.platform }} on Xcode ${{ matrix.xcode }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        platform: [macOS, iOS, tvOS, watchOS]
        xcode: [^13, ^14] # ^15
        os: [macos-12, macos-13]
        exclude:
          - xcode: ^15
            os: macos-12
          - xcode: ^13
            os: macos-13
    steps:
      - uses: actions/checkout@v4

      - uses: mxcl/xcodebuild@v1
        with:
          xcode: ${{ matrix.xcode }}
          platform: ${{ matrix.platform }}
          action: build
          configuration: debug
          scheme: Aptabase

      - uses: mxcl/xcodebuild@v1
        with:
          xcode: ${{ matrix.xcode }}
          platform: ${{ matrix.platform }}
          action: test
          configuration: debug
          scheme: AptabaseTests