name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Platform ${{ matrix.platform }} on Xcode ${{ matrix.xcode }} + ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        platform: [macOS, iOS, tvOS, watchOS]
        xcode: [^14, ^15]
        os: [macos-13]
        include:
          - xcode: ^13
            os: macos-12
    steps:
      - uses: actions/checkout@v4

      - uses: mxcl/xcodebuild@v1
        with:
          xcode: ${{ matrix.xcode }}
          platform: ${{ matrix.platform }}
          action: build
          configuration: release

      - uses: mxcl/xcodebuild@v1
        with:
          xcode: ${{ matrix.xcode }}
          platform: ${{ matrix.platform }}
          action: test
          configuration: release
          scheme: AptabaseTests