name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Platform ${{ matrix.platform }} on Xcode ${{ matrix.xcode }} + ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        platform:
          - macOS
          - watchOS
          - tvOS
          - iOS
        include:
          - xcode: ^13
            os: "macos-12"
          - xcode: ^14
            os: "macos-13"
          - xcode: ^15
            os: "macos-13"
    steps:
      - uses: actions/checkout@v4

      - uses: mxcl/xcodebuild@v1
        with:
          xcode: ${{ matrix.xcode }}
          platform: ${{ matrix.platform }}
          action: build
          configuration: release

      - uses: mxcl/xcodebuild@v1
        with:
          xcode: ${{ matrix.xcode }}
          platform: ${{ matrix.platform }}
          action: test
          configuration: release